// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xamcrkksqvvwihmatvcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhbWNya2tzcXZ2d2lobWF0dmNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDE4NzEsImV4cCI6MjA2NDUxNzg3MX0._Uhe9sXzmIOMcnEc1Y7flXOxQuAgLc4JS3VaCRzMh1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);