import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface LanguageContextType {
  language: 'en' | 'es' | 'ar' | 'fr' | 'de';
  setLanguage: (lang: 'en' | 'es' | 'ar' | 'fr' | 'de') => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // KDS Main Interface
    'kds.title': 'Kitchen Display System',
    'kds.activeOrders': 'Active Orders',
    'kds.moreItems': 'More Items',
    'kds.back': 'Back',
    'kds.enterOrderNumber': 'Enter order number to finish',
    'kds.finish': 'Finish',
    'kds.noCategoriesSelected': 'No categories selected',
    'kds.noActiveOrders': 'No active orders',
    'kds.ordersWillAppear': 'Orders will appear here when received',
    'kds.hint': 'Hint',
    'kds.disconnected': 'Database disconnected',
    'kds.disconnectedMessage': 'Please check your database connection settings.',
    'kds.enableSoundsPrompt': 'Click to enable sounds',
    'kds.enableSounds': 'Enable Sounds',
    'kds.complete': 'Finish',
    'kds.disableSounds': 'Disenable Sounds',
    'kds.newOrderNotification': 'New Order Received',
    'common.processing': 'Processing....',
    'order.items': 'Items',
    'order.item': 'Item',
    'order.modifiers': 'Modifiers',
    // Category Names
    'category.Food': 'Food',
    'category.Bavarage': 'Beverage',
    'category.desserts': 'Desserts',
    'category.Pizza': 'Pizza',
    'category.Shishah': 'Shisha',
    'kds.defaultCategoryName': 'Kitchen',
    // Error Messages
    'kds.errors.orderNumberRequired': 'Order number is required',
    'kds.errors.orderNotFound': 'Order not found',
    'kds.errors.finishFailed': 'Failed to finish order',
    'kds.errors.loadFailed': 'Failed to load orders',
    'kds.errors.categoryLoadFailed': 'Failed to load category information',
    // Success Messages
    'kds.success.orderFinished': 'Order finished successfully',
    // Order Details
    'order.orderNumber': 'Order ',
    'order.fullScreen': 'Full Screen',
    'order.finishOrder': 'Finish Order',
    'order.back': 'Back',
    'order.orderItems': 'Order Items',
    'order.orderNotes': 'Order Notes',
    'order.specialInstructions': 'Special Instructions',
    'order.orderTime': 'Order Time',
    'order.orderSummary': 'Order Summary',
    'order.totalItems': 'Total Items',
    'order.itemTypes': 'Item Types',
    'order.orderCreated': 'Order Created',
    'order.status': 'Status',
    'order.completed': 'Completed',
    'order.pending': 'Pending',
    'order.expired': 'Order Late',
    // Help Section
    'kds.help.title': 'How to Use the Kitchen Display System',
    'kds.help.description': 'This guide explains how to use the Kitchen Display System to manage orders efficiently.',
    'kds.help.enterOrder': 'Enter an order number in the input field and press Enter to mark it as finished.',
    'kds.help.fullScreen': 'Enter an order number in the input field click the "+" button to view an order in full-screen mode for detailed information.',
    'kds.help.closeFullScreen': 'Press "-" or "Escape" to exit full-screen mode.',
    'kds.help.mute': 'Click the speaker icon to mute or unmute notification sounds for 10 seconds.',
    'kds.help.settings': 'Access the settings panel by clicking the gear icon to configure categories, sounds, themes, language, or database settings.',
    // Settings
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.soundSettings': 'Sound Settings',
    'settings.enableSounds': 'Enable Sounds',
    'settings.newOrderSound': 'New Order Sound',
    'settings.nearFinishedSound': 'Near Finished Sound',
    'settings.volume': 'Volume',
    'settings.databaseConfig': 'Database Configuration',
    'settings.server': 'Server',
    'settings.serverPlaceholder': 'Server name or IP',
    'settings.database': 'Database',
    'settings.disconnectedPassword': 'Disconnected Database Password',
    'settings.categories': 'Categories',
    'settings.databasePlaceholder': 'Database name',
    'settings.user': 'User',
    'settings.userPlaceholder': 'Database user',
    'settings.password': 'Password',
    'settings.passwordPlaceholder': 'Database password',
    'settings.reconnect': 'Reconnect Database',
    'settings.reconnectDatabase': 'Reconnect Database',
    'settings.reconnecting': 'Reconnecting...',
    'settings.accessSettings': 'Access Settings',
    'settings.enterPassword': 'Enter Password',
    'settings.passwordPrompt': 'Enter password to access settings',
    'settings.invalidPassword': 'Invalid password. Please try again.',
    'settings.uploadCustom': 'Upload Custom',
    'settings.replaceCustom': 'Replace Custom',
    'settings.uploading': 'Uploading...',
    'settings.removeCustomSound': 'Remove custom sound',
    'settings.customSound': 'Custom sound',
    'settings.invalidAudioFile': 'Please select a valid audio file.',
    'settings.uploadError': 'Error uploading sound file',
    'settings.removeSoundError': 'Error removing custom sound',
    'settings.stopAudio': 'Stop Playing Audio',
    'settings.close': 'Close Settings',
    'settings.reconnectFailed': 'Failed to reconnect. Check DB config.',
    'settings.connectionError': 'Connection error',
    'settings.connectionSuccess': 'Connection successful!',
    'settings.english': 'English',
    'settings.spanish': 'Spanish',
    'settings.arabic': 'Arabic',
    'settings.french': 'French',
    'settings.german': 'German',
  },
  es: {
    // KDS Main Interface
    'kds.title': 'Sistema de Pantalla de Cocina',
    'kds.activeOrders': 'Órdenes Activas',
    'kds.moreItems': 'Más Artículos',
    'kds.back': 'Atrás',
    'kds.enterOrderNumber': 'Ingrese número de orden para finalizar',
    'kds.finish': 'Finalizar',
    'kds.noActiveOrders': 'No hay órdenes activas',
    'kds.ordersWillAppear': 'Las órdenes aparecerán aquí cuando se reciban',
    'kds.hint': 'Pista',
    'kds.disconnected': 'Base de datos desconectada',
    'kds.disconnectedMessage': 'Por favor, verifique la configuración de conexión a la base de datos.',
    'kds.enableSoundsPrompt': 'Haga clic para habilitar sonidos',
    'kds.enableSounds': 'Habilitar Sonidos',
    'kds.disableSounds': 'Deshabilitar Sonidos',
    'kds.newOrderNotification': 'Nueva Orden Recibida',
    'common.processing': 'Procesando....',
    'order.items': 'Artículos',
    'order.item': 'Artículo',
    'order.modifiers': 'Modificadores',
    // Category Names
    'category.Food': 'Comida',
    'category.Bavarage': 'Bebida',
    'category.desserts': 'Postres',
    'category.Pizza': 'Pizza',
    'category.Shishah': 'Shisha',
    'kds.defaultCategoryName': 'Cocina',
    // Error Messages
    'kds.errors.orderNumberRequired': 'El número de orden es requerido',
    'kds.errors.orderNotFound': 'Orden no encontrada',
    'kds.errors.finishFailed': 'Error al finalizar la orden',
    'kds.errors.loadFailed': 'Error al cargar las órdenes',
    'kds.errors.categoryLoadFailed': 'Error al cargar la información de la categoría',
    // Success Messages
    'kds.success.orderFinished': 'Orden finalizada exitosamente',
    // Order Details
    'order.orderNumber': 'Orden ',
    'order.fullScreen': 'Pantalla Completa',
    'order.finishOrder': 'Finalizar Orden',
    'order.back': 'Atrás',
    'order.orderItems': 'Artículos del Pedido',
    'order.orderNotes': 'Notas del Pedido',
    'order.specialInstructions': 'Instrucciones Especiales',
    'order.orderTime': 'Hora del Pedido',
    'order.orderSummary': 'Resumen del Pedido',
    'order.totalItems': 'Total de Artículos',
    'order.itemTypes': 'Tipos de Artículo',
    'order.orderCreated': 'Pedido Creado',
    'order.status': 'Estado',
    'order.completed': 'Completado',
    'order.pending': 'Pendiente',
    'order.expired': 'Orden Retrasada',
    // Help Section
    'kds.help.title': 'Cómo Usar el Sistema de Pantalla de Cocina',
    'kds.help.description': 'Esta guía explica cómo usar el Sistema de Pantalla de Cocina para gestionar órdenes de manera eficiente.',
    'kds.help.enterOrder': 'Ingrese un número de orden en el campo de entrada y presione Enter para marcarlo como finalizado.',
    'kds.help.fullScreen': 'Ingrese un número de orden en el campo de entrada y Haga clic en el botón "+" para ver una orden en modo de pantalla completa para obtener información detallada.',
    'kds.help.closeFullScreen': 'Presione "-" o "Escape" para salir del modo de pantalla completa.',
    'kds.help.mute': 'Haga clic en el icono del altavoz para silenciar o reactivar los sonidos de notificación durante 10 segundos.',
    'kds.help.settings': 'Acceda al panel de configuraciones haciendo clic en el icono de engranaje para ajustar categorías, sonidos, temas, idioma o configuraciones de la base de datos.',
    // Settings
    'settings.title': 'Configuraciones',
    'settings.language': 'Idioma',
    'settings.theme': 'Tema',
    'settings.light': 'Claro',
    'settings.dark': 'Oscuro',
    'settings.soundSettings': 'Configuración de Sonido',
    'settings.enableSounds': 'Habilitar Sonidos',
    'settings.newOrderSound': 'Sonido de Nueva Orden',
    'settings.nearFinishedSound': 'Sonido de Orden Casi Finalizada',
    'settings.volume': 'Volumen',
    'settings.databaseConfig': 'Configuración de Base de Datos',
    'settings.server': 'Servidor',
    'settings.serverPlaceholder': 'Nombre del servidor o IP',
    'settings.database': 'Base de Datos',
    'settings.databasePlaceholder': 'Nombre de la base de datos',
    'settings.user': 'Usuario',
    'settings.userPlaceholder': 'Usuario de la base de datos',
    'settings.password': 'Contraseña',
    'settings.passwordPlaceholder': 'Contraseña de la base de datos',
    'settings.reconnect': 'Reconectar Base de Datos',
    'settings.reconnectDatabase': 'Reconectar Base de Datos',
    'settings.reconnecting': 'Reconectando...',
    'settings.accessSettings': 'Acceder a Configuraciones',
    'settings.enterPassword': 'Ingresar Contraseña',
    'settings.passwordPrompt': 'Ingrese la contraseña para acceder a las configuraciones',
    'settings.invalidPassword': 'Contraseña inválida. Inténtalo de nuevo.',
    'settings.uploadCustom': 'Subir Personalizado',
    'settings.replaceCustom': 'Reemplazar Personalizado',
    'settings.uploading': 'Subiendo...',
    'settings.removeCustomSound': 'Eliminar sonido personalizado',
    'settings.customSound': 'Sonido personalizado',
    'settings.invalidAudioFile': 'Por favor, selecciona un archivo de audio válido.',
    'settings.uploadError': 'Error al subir el archivo de sonido',
    'settings.removeSoundError': 'Error al eliminar el sonido personalizado',
    'settings.stopAudio': 'Detener la reproducción de audio',
    'settings.close': 'Cerrar Configuraciones',
    'settings.reconnectFailed': 'Error al reconectar. Verifica la configuración de la base de datos.',
    'settings.connectionError': 'Error de conexión',
    'settings.connectionSuccess': '¡Conexión exitosa!',
    'settings.english': 'English',
    'settings.spanish': 'Spanish',
    'settings.arabic': 'Arabic',
    'settings.french': 'French',
    'settings.german': 'German',
  },
  ar: {
    // KDS Main Interface
    'kds.title': 'نظام عرض المطبخ',
    'kds.activeOrders': 'الطلبات النشطة',
    'kds.moreItems': 'المزيد من العناصر',
    'kds.enterOrderNumber': 'أدخل رقم الطلب للإنهاء',
    'kds.back': 'رجوع',
    'kds.finish': 'إنهاء',
    'kds.noCategoriesSelected': 'لم يتم اختيار أي فئات',
    'kds.noActiveOrders': 'لا توجد طلبات نشطة',
    'kds.ordersWillAppear': 'ستظهر الطلبات هنا عند استلامها',
    'kds.hint': 'تلميح',
    'kds.disconnected': 'قاعدة البيانات غير متصلة',
    'kds.disconnectedMessage': 'يرجى التحقق من إعدادات اتصال قاعدة البيانات.',
    'kds.enableSoundsPrompt': 'تفعيل الأصوات',
    'kds.complete': 'إنهاء',
    'kds.disableSounds': 'تعطيل الأصوات',
    'kds.enableSounds': 'تفعيل الأصوات',
    'kds.newOrderNotification': 'تم استلام طلب جديد',
    'common.processing': 'جارٍ المعالجة....',
    'order.items': 'عناصر',
    'order.item': 'عنصر',
    'order.modifiers': 'الإضافات',
    // Category Names
    'category.Food': 'طعام',
    'category.Bavarage': 'مشروبات',
    'category.desserts': 'حلويات',
    'category.Pizza': 'بيتزا',
    'category.Shishah': 'شيشة',
    'kds.defaultCategoryName': 'المطبخ',
    // Error Messages
    'kds.errors.orderNumberRequired': 'رقم الطلب مطلوب',
    'kds.errors.orderNotFound': 'الطلب غير موجود',
    'kds.errors.finishFailed': 'فشل في إنهاء الطلب',
    'kds.errors.loadFailed': 'فشل في تحميل الطلبات',
    'kds.errors.categoryLoadFailed': 'فشل في تحميل معلومات الفئة',
    // Success Messages
    'kds.success.orderFinished': 'تم إنهاء الطلب بنجاح',
    // Order Details
    'order.orderNumber': 'طلب رقم ',
    'order.fullScreen': 'شاشة كاملة',
    'order.finishOrder': 'إنهاء الطلب',
    'order.back': 'رجوع',
    'order.orderItems': 'عناصر الطلب',
    'order.orderNotes': 'ملاحظات الطلب',
    'order.specialInstructions': 'تعليمات خاصة',
    'order.orderTime': 'وقت الطلب',
    'order.orderSummary': 'ملخص الطلب',
    'order.totalItems': 'إجمالي العناصر',
    'order.itemTypes': 'أنواع العناصر',
    'order.orderCreated': 'الطلب أنشئ في',
    'order.status': 'الحالة',
    'order.completed': 'مكتمل',
    'order.pending': 'معلق',
    'order.expired': 'الطلب متأخر',
    // Help Section
    'kds.help.title': 'كيفية استخدام نظام عرض المطبخ',
    'kds.help.description': 'يشرح هذا الدليل كيفية استخدام نظام عرض المطبخ لإدارة الطلبات بكفاءة.',
    'kds.help.enterOrder': 'أدخل رقم الطلب في حقل الإدخال واضغط على Enter لتعليمه كمنتهٍ.',
    'kds.help.fullScreen': '  أدخل رقم الطلب في حقل الإدخال ثم انقر على زر "+" لعرض الطلب فى وضع الشاشة الكاملة للحصول على معلومات تفصيلية',
    'kds.help.closeFullScreen': 'اضغط على "-" أو "Escape" للخروج من وضع الشاشة الكاملة.',
    'kds.help.mute': 'انقر على أيقونة السماعة لكتم أو إعادة تفعيل أصوات الإشعارات لمدة 10 ثوانٍ.',
    'kds.help.settings': 'قم بالوصول إلى لوحة الإعدادات بالنقر على أيقونة الترس لتكوين الفئات، الأصوات، المظاهر، اللغة، أو إعدادات قاعدة البيانات.',
    // Settings
    'settings.title': 'الإعدادات',
    'settings.language': 'اللغة',
    'settings.theme': 'المظهر',
    'settings.light': 'فاتح',
    'settings.dark': 'داكن',
    'settings.soundSettings': 'إعدادات الصوت',
    'settings.enableSounds': 'تفعيل الأصوات',
    'settings.newOrderSound': 'صوت طلب جديد',
    'settings.nearFinishedSound': 'صوت الطلب القريب من الانتهاء',
    'settings.volume': 'مستوى الصوت',
    'settings.databaseConfig': 'تكوين قاعدة البيانات',
    'settings.server': 'الخادم',
    'settings.categories': 'الفئات',
    'settings.disconnectedPassword': 'كلمة المرور لقاعدة البيانات الغير المتصلة',
    'settings.serverPlaceholder': 'اسم الخادم أو عنوان IP',
    'settings.database': 'قاعدة البيانات',
    'settings.databasePlaceholder': 'اسم قاعدة البيانات',
    'settings.user': 'المستخدم',
    'settings.userPlaceholder': 'مستخدم قاعدة البيانات',
    'settings.password': 'كلمة المرور',
    'settings.passwordPlaceholder': 'كلمة مرور قاعدة البيانات',
    'settings.reconnect': 'إعادة الاتصال بقاعدة البيانات',
    'settings.reconnectDatabase': 'إعادة الاتصال بقاعدة البيانات',
    'settings.reconnecting': 'جارٍ إعادة الاتصال...',
    'settings.accessSettings': 'الوصول إلى الإعدادات',
    'settings.enterPassword': 'أدخل كلمة المرور',
    'settings.passwordPrompt': 'أدخل كلمة المرور للوصول إلى الإعدادات',
    'settings.invalidPassword': 'كلمة مرور غير صحيحة. حاول مرة أخرى.',
    'settings.uploadCustom': 'تحميل مخصص',
    'settings.replaceCustom': 'استبدال المخصص',
    'settings.uploading': 'جارٍ التحميل...',
    'settings.removeCustomSound': 'إزالة الصوت المخصص',
    'settings.customSound': 'صوت مخصص',
    'settings.invalidAudioFile': 'يرجى اختيار ملف صوتي صالح.',
    'settings.uploadError': 'خطأ في تحميل ملف الصوت',
    'settings.removeSoundError': 'خطأ في إزالة الصوت المخصص',
    'settings.stopAudio': 'إيقاف تشغيل الصوت',
    'settings.close': 'إغلاق الإعدادات',
    'settings.reconnectFailed': 'فشل في إعادة الاتصال. تحقق من تكوين قاعدة البيانات.',
    'settings.connectionError': 'خطأ في الاتصال',
    'settings.connectionSuccess': 'الاتصال ناجح!',
    'settings.english': 'الإنجليزية',
    'settings.spanish': 'الإسبانية',
    'settings.arabic': 'العربية',
    'settings.french': 'الفرنسية',
    'settings.german': 'الألمانية',
  },
  fr: {
    // KDS Main Interface
    'kds.title': 'Système d\'Affichage de Cuisine',
    'kds.activeOrders': 'Commandes Actives',
    'kds.enterOrderNumber': 'Entrez le numéro de commande pour terminer',
    'kds.finish': 'Terminer',
    'kds.noCategoriesSelected': 'Aucune catégorie sélectionnée',
    'kds.noActiveOrders': 'Aucune commande active',
    'kds.ordersWillAppear': 'Les commandes apparaîtront ici lorsqu\'elles seront reçues',
    'kds.hint': 'Astuce',
    'kds.enableSoundsPrompt': 'Cliquez pour activer les sons',
    'kds.enableSounds': 'Activer les Sons',
    'kds.complete': 'Terminer',
    'kds.disableSounds': 'Désactiver les Sons',
    'kds.newOrderNotification': 'Nouvelle Commande Reçue',
    'common.processing': 'Traitement en cours....',
    'order.items': 'Articles',
    'order.item': 'Article',
    // Category Names
    'category.Food': 'Nourriture',
    'category.Bavarage': 'Boisson',
    'category.desserts': 'Desserts',
    'category.Pizza': 'Pizza',
    'category.Shishah': 'Chicha',
    'kds.defaultCategoryName': 'Cuisine',
    // Error Messages
    'kds.errors.orderNumberRequired': 'Le numéro de commande est requis',
    'kds.errors.orderNotFound': 'Commande non trouvée',
    'kds.errors.finishFailed': 'Échec de la finalisation de la commande',
    'kds.errors.loadFailed': 'Échec du chargement des commandes',
    'kds.errors.categoryLoadFailed': 'Échec du chargement des informations de catégorie',
    // Success Messages
    'kds.success.orderFinished': 'Commande terminée avec succès',
    // Order Details
    'order.orderNumber': 'Commande ',
    'order.fullScreen': 'Plein Écran',
    'order.finishOrder': 'Terminer la Commande',
    'order.back': 'Retour',
    'order.orderItems': 'Articles de la Commande',
    'order.orderNotes': 'Notes de la Commande',
    'order.specialInstructions': 'Instructions Spéciales',
    'order.orderTime': 'Heure de la Commande',
    'order.orderSummary': 'Résumé de la Commande',
    'order.totalItems': 'Total des Articles',
    'order.itemTypes': 'Types d\'Articles',
    'order.orderCreated': 'Commande Créée',
    'order.status': 'Statut',
    'order.completed': 'Terminé',
    'order.pending': 'En Attente',
    'order.expired': 'Commande en Retard',
    // Help Section
    'kds.help.title': 'Comment Utiliser le Système d\'Affichage de Cuisine',
    'kds.help.description': 'Ce guide explique comment utiliser le Système d\'Affichage de Cuisine pour gérer les commandes efficacement.',
    'kds.help.enterOrder': 'Entrez un numéro de commande dans le champ de saisie et appuyez sur Entrée pour la marquer comme terminée.',
    'kds.help.fullScreen': 'Cliquez sur le bouton "+" pour afficher une commande en mode plein écran pour plus de détails.',
    'kds.help.closeFullScreen': 'Appuyez sur "-" ou "Échap" pour quitter le mode plein écran.',
    'kds.help.mute': 'Cliquez sur l\'icône du haut-parleur pour activer ou désactiver les sons de notification pendant 10 secondes.',
    'kds.help.settings': 'Accédez au panneau des paramètres en cliquant sur l\'icône d\'engrenage pour configurer les catégories, les sons, les thèmes, la langue ou les paramètres de la base de données.',
    'kds.help.disconnected': 'Si la base de données est déconnectée, utilisez le mot de passe "911" pour accéder aux paramètres et vous reconnecter.',
    // Settings
    'settings.title': 'Paramètres',
    'settings.language': 'Langue',
    'settings.theme': 'Thème',
    'settings.light': 'Clair',
    'settings.dark': 'Sombre',
    'settings.soundSettings': 'Paramètres Sonores',
    'settings.enableSounds': 'Activer les Sons',
    'settings.newOrderSound': 'Son de Nouvelle Commande',
    'settings.nearFinishedSound': 'Son de Commande Presque Terminée',
    'settings.volume': 'Volume',
    'settings.databaseConfig': 'Configuration de la Base de Données',
    'settings.server': 'Serveur',
    'settings.serverPlaceholder': 'Nom du serveur ou IP',
    'settings.database': 'Base de Données',
    'settings.databasePlaceholder': 'Nom de la base de données',
    'settings.user': 'Utilisateur',
    'settings.categories': 'Utilisateur',
    'settings.userPlaceholder': 'Utilisateur de la base de données',
    'settings.password': 'Mot de Passe',
    'settings.passwordPlaceholder': 'Mot de passe de la base de données',
    'settings.reconnect': 'Reconnecter la Base de Données',
    'settings.reconnectDatabase': 'Reconnecter la Base de Données',
    'settings.reconnecting': 'Reconnexion...',
    'settings.accessSettings': 'Accéder aux Paramètres',
    'settings.enterPassword': 'Entrez le Mot de Passe',
    'settings.passwordPrompt': 'Entrez le mot de passe pour accéder aux paramètres',
    'settings.invalidPassword': 'Mot de passe invalide. Veuillez réessayer.',
    'settings.uploadCustom': 'Télécharger Personnalisé',
    'settings.replaceCustom': 'Remplacer Personnalisé',
    'settings.uploading': 'Téléchargement...',
    'settings.removeCustomSound': 'Supprimer le Son Personnalisé',
    'settings.customSound': 'Son Personnalisé',
    'settings.invalidAudioFile': 'Veuillez sélectionner un fichier audio valide.',
    'settings.uploadError': 'Erreur lors du téléchargement du fichier audio',
    'settings.removeSoundError': 'Erreur lors de la suppression du son personnalisé',
    'settings.stopAudio': 'Arrêter la Lecture Audio',
    'settings.close': 'Fermer les Paramètres',
    'settings.reconnectFailed': 'Échec de la reconnexion. Vérifiez la configuration de la base de données.',
    'settings.connectionError': 'Erreur de Connexion',
    'settings.connectionSuccess': 'Connexion Réussie !',
    'settings.english': 'Anglais',
    'settings.spanish': 'Espagnol',
    'settings.arabic': 'Arabe',
    'settings.french': 'Français',
    'settings.german': 'Allemand',
  },
  de: {
    // KDS Main Interface
    'kds.title': 'Küchenanzeigesystem',
    'kds.activeOrders': 'Aktive Bestellungen',
    'kds.enterOrderNumber': 'Bestellnummer zum Abschließen eingeben',
    'kds.finish': 'Abschließen',
    'kds.noActiveOrders': 'Keine aktiven Bestellungen',
    'kds.ordersWillAppear': 'Bestellungen erscheinen hier, wenn sie empfangen werden',
    'kds.hint': 'Hinweis',
    'kds.enableSoundsPrompt': 'Klicken, um Töne zu aktivieren',
    'kds.enableSounds': 'Töne Aktivieren',
    'kds.complete': 'Abschließen',
    'kds.disableSounds': 'Töne Deaktivieren',
    'kds.newOrderNotification': 'Neue Bestellung Erhalten',
    'common.processing': 'Verarbeitung....',
    'order.items': 'Artikel',
    'order.item': 'Artikel',
    // Category Names
    'category.Food': 'Essen',
    'category.Bavarage': 'Getränk',
    'category.desserts': 'Desserts',
    'category.Pizza': 'Pizza',
    'category.Shishah': 'Shisha',
    'kds.defaultCategoryName': 'Küche',
    // Error Messages
    'kds.errors.orderNumberRequired': 'Bestellnummer ist erforderlich',
    'kds.errors.orderNotFound': 'Bestellung nicht gefunden',
    'kds.errors.finishFailed': 'Fehler beim Abschließen der Bestellung',
    'kds.errors.loadFailed': 'Fehler beim Laden der Bestellungen',
    'kds.errors.categoryLoadFailed': 'Fehler beim Laden der Kategorieinformationen',
    // Success Messages
    'kds.success.orderFinished': 'Bestellung erfolgreich abgeschlossen',
    // Order Details
    'order.orderNumber': 'Bestellung ',
    'order.fullScreen': 'Vollbild',
    'order.finishOrder': 'Bestellung Abschließen',
    'order.back': 'Zurück',
    'order.orderItems': 'Bestellartikel',
    'order.orderNotes': 'Bestellnotizen',
    'order.specialInstructions': 'Spezielle Anweisungen',
    'order.orderTime': 'Bestellzeit',
    'order.orderSummary': 'Bestellübersicht',
    'order.totalItems': 'Gesamtanzahl der Artikel',
    'order.itemTypes': 'Artikeltypen',
    'order.orderCreated': 'Bestellung Erestellt',
    'order.status': 'Status',
    'order.completed': 'Abgeschlossen',
    'order.pending': 'Ausstehend',
    'order.expired': 'Bestellung Verspätet',
    // Help Section
    'kds.help.title': 'Wie man das Küchenanzeigesystem Verwendet',
    'kds.help.description': 'Diese Anleitung erklärt, wie man das Küchenanzeigesystem nutzt, um Bestellungen effizient zu verwalten.',
    'kds.help.enterOrder': 'Geben Sie eine Bestellnummer in das Eingabefeld ein und drücken Sie Enter, um sie als abgeschlossen zu markieren.',
    'kds.help.fullScreen': 'Klicken Sie auf die "+"-Schaltfläche, um eine Bestellung im Vollbildmodus für detaillierte Informationen anzuzeigen.',
    'kds.help.closeFullScreen': 'Drücken Sie "-" oder "Escape", um den Vollbildmodus zu verlassen.',
    'kds.help.mute': 'Klicken Sie auf das Lautsprechersymbol, um Benachrichtigungstöne für 10 Sekunden stummzuschalten oder zu reaktivieren.',
    'kds.help.settings': 'Greifen Sie auf das Einstellungspanel zu, indem Sie auf das Zahnradsymbol klicken, um Kategorien, Töne, Themen, Sprache oder Datenbankeinstellungen zu konfigurieren.',
    'kds.help.disconnected': 'Wenn die Datenbank nicht verbunden ist, verwenden Sie das Passwort "911", um auf die Einstellungen zuzugreifen und sich erneut zu verbinden.',
    // Settings
    'settings.title': 'Einstellungen',
    'settings.language': 'Sprache',
    'settings.theme': 'Thema',
    'settings.light': 'Hell',
    'settings.dark': 'Dunkel',
    'settings.soundSettings': 'Toneinstellungen',
    'settings.enableSounds': 'Töne Aktivieren',
    'settings.newOrderSound': 'Ton für Neue Bestellung',
    'settings.nearFinishedSound': 'Ton für Fast Fertige Bestellung',
    'settings.volume': 'Lautstärke',
    'settings.databaseConfig': 'Datenbankkonfiguration',
    'settings.server': 'Server',
    'settings.serverPlaceholder': 'Servername oder IP',
    'settings.disconnectedPassword': 'Passwort für getrennte Datenbank',
    'settings.database': 'Datenbank',
    'settings.databasePlaceholder': 'Datenbankname',
    'settings.user': 'Benutzer',
    'settings.userPlaceholder': 'Datenbankbenutzer',
    'settings.password': 'Passwort',
    'settings.passwordPlaceholder': 'Datenbankpasswort',
    'settings.reconnect': 'Datenbank Neu Verbinden',
    'settings.reconnectDatabase': 'Datenbank Neu Verbinden',
    'settings.reconnecting': 'Wird neu verbunden...',
    'settings.accessSettings': 'Zugriff auf Einstellungen',
    'settings.enterPassword': 'Passwort Eingeben',
    'settings.passwordPrompt': 'Passwort eingeben, um auf Einstellungen zuzugreifen',
    'settings.invalidPassword': 'Ungültiges Passwort. Bitte versuchen Sie es erneut.',
    'settings.uploadCustom': 'Benutzerdefiniert Hochladen',
    'settings.replaceCustom': 'Benutzerdefiniert Ersetzen',
    'settings.uploading': 'Hochladen...',
    'settings.removeCustomSound': 'Benutzerdefinierten Ton Entfernen',
    'settings.customSound': 'Benutzerdefinierter Ton',
    'settings.invalidAudioFile': 'Bitte wählen Sie eine gültige Audiodatei aus.',
    'settings.uploadError': 'Fehler beim Hochladen der Audiodatei',
    'settings.removeSoundError': 'Fehler beim Entfernen des benutzerdefinierten Tons',
    'settings.stopAudio': 'Audiowiedergabe Stoppen',
    'settings.close': 'Einstellungen Schließen',
    'settings.reconnectFailed': 'Wiederverbindung fehlgeschlagen. Überprüfen Sie die Datenbankkonfiguration.',
    'settings.connectionError': 'Verbindungsfehler',
    'settings.connectionSuccess': 'Verbindung Erfolgreich!',
    'settings.english': 'Englisch',
    'settings.spanish': 'Spanisch',
    'settings.arabic': 'Arabisch',
    'settings.french': 'Französisch',
    'settings.german': 'Deutsch',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'es' | 'ar' | 'fr' | 'de'>(() => {
    const savedLanguage = localStorage.getItem('kds_language');
    return (savedLanguage as 'en' | 'es' | 'ar' | 'fr' | 'de') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('kds_language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};